apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: nestjs-microservice
build:
  artifacts:
    - image: keys-api
      context: .
      sync:
        manual:
          - src: /src/**/*.ts
            dest: ./services/key-management
      docker:
        dockerfile: ./services/key-management/Dockerfile
    - image: web3-api
      context: .
      sync:
        manual:
          - src: /src/**/*.ts
            dest: ./services/web3-token
      docker:
        dockerfile: ./services/web3-token/Dockerfile
  local:
    push: false
    concurrency: 1
manifests:
  helm:
    releases:
      - name: ingress
        chartPath: ./infra/helm/ingress
        # skipBuildDependencies: true
      - name: kafka
        chartPath: ./infra/helm/kafka
        namespace: kafka
        createNamespace: true
        skipBuildDependencies: true
      - name: keycloak
        chartPath: ./infra/helm/keycloak
        namespace: keycloak
        createNamespace: true
        # skipBuildDependencies: true
      - name: keys-api
        chartPath: ./infra/helm/keys
        valuesFiles:
          - ./infra/helm/common/values.yaml
        setValues:
          image.repository: keys-api
        # skipBuildDependencies: true
      - name: web3-api
        chartPath: ./infra/helm/web3
        valuesFiles:
          - ./infra/helm/common/values.yaml
        setValues:
          image.repository: web3-api
        # skipBuildDependencies: true
deploy:
  helm: {}
