apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: nestjs-microservice
build:
  artifacts:
    - image: keys-api
      context: ../
      sync:
        manual:
          - src: /src/**/*.ts
            dest: ./services/keys
      docker:
        dockerfile: ./services/keys/Dockerfile
    - image: web3-api
      context: ../
      sync:
        manual:
          - src: /src/**/*.ts
            dest: ./services/web3
      docker:
        dockerfile: ./services/web3/Dockerfile
  local:
    push: false
    concurrency: 1
manifests:
  helm:
    releases:
      - name: ingress
        chartPath: helm/ingress
      - name: kafka
        chartPath: helm/kafka
        namespace: kafka
        createNamespace: true
      - name: keycloak
        chartPath: helm/keycloak
        namespace: keycloak
        createNamespace: true
      - name: postgresql
        chartPath: helm/postgresql
        valuesFiles:
          - ./helm/common/values.yaml
        namespace: database
        createNamespace: true
      - name: keys-api
        chartPath: helm/keys
        valuesFiles:
          - ./helm/common/values.yaml
        setValues:
          image.repository: keys-api
      - name: web3-api
        chartPath: helm/web3
        valuesFiles:
          - ./helm/common/values.yaml
        setValues:
          image.repository: web3-api
deploy:
  helm: {}
