apiVersion: v2
name: Postgres
description: Postgres Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 15.5.5
    repository: oci://registry-1.docker.io/bitnamicharts
