apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web3
  template:
    metadata:
      labels:
        app: web3
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          env:
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: DB_URL
              value: {{ .Values.postgresql.auth.dbUrl }}
            - name: KAKFA_BROKER
              value: {{ .Values.kafkaBroker }}
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}