apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web3
  template:
    metadata:
      labels:
        app: web3
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          env:
            - name: WEB3_DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: WEB3_DB_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: WEB3_DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: WEB3_DB_HOST
              value: {{ .Values.postgresql.auth.dbUrl }}
            - name: KAFKA_BROKER
              value: {{ .Values.kafkaBroker }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}