apiVersion: v2
name: keycloak
description: Keycloak Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: keycloak
    version: 21.4.1
    repository: oci://registry-1.docker.io/bitnamicharts
