apiVersion: apps/v1
kind: Deployment
metadata:
  name: keys-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keys
  template:
    metadata:
      labels:
        app: keys
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          # env:
          #   - name: DB_NAME
          #     value: {{ .Values.postgresql.auth.database }}
          #   - name: DB_USERNAME
          #     value: {{ .Values.postgresql.auth.username }}
          #   - name: DB_PASSWORD
          #     value: {{ .Values.postgresql.auth.password }}
          #   - name: DB_URL
          #     value: {{ .Values.postgresql.auth.dbUrl }}
          #   - name: NODE_ENV
          #     value: {{ .Values.nodeEnv }}