apiVersion: apps/v1
kind: Deployment
metadata:
  name: keys-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keys
  template:
    metadata:
      labels:
        app: keys
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          env:
            - name: KEY_DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: KEY_DB_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: KEY_DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: KEY_DB_HOST
              value: {{ .Values.postgresql.auth.dbUrl }}
            - name: KAFKA_BROKER
              value: {{ .Values.kafkaBroker }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}